source 'https://rubygems.org'
ruby '2.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.4'

# Use postgres as the database for Active Record
gem 'mysql2'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.2'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

gem 'thin', '~> 1.6.0'
gem 'activeadmin', github: 'gregbell/active_admin'
gem 'faker'
gem 'rabl'

group :development do
  gem 'rubocop'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'byebug'
  gem 'shoulda'
end

group :test do
  gem 'simplecov', '~> 0.7.1', :require => false
  # gem 'database_cleaner', '1.0.1'
  gem 'codeclimate-test-reporter', require: nil
  # gem 'capybara'
  # gem 'capybara-webkit'
  # gem 'selenium-webdriver'
  # gem 'headless'
  gem 'mocha'
end

group :production do
end